language: node_js

#Request root permissions to the TravisCI runtime environment
sudo: required

#Tell TravisCI that we're using docker to run our tests
services:
    - docker

# Build test container
before_install:
  - docker build -t everyrocketlaunch.com-test -f ./frontend/Dockerfile.test .

#Run our test Docker container
script:
  # - docker run everyrocketlaunch.com-test
  - 'true'

#Build our deployment container
before_deploy:
  - docker build -t frontend/everyrocketlaunch.com ./frontend/

#Run our deployment container via shell script if commiting to the master branch
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./frontend/scripts/deploy.sh
  on:
    branch: master